sw = {
    "manufacturer": {"name": "cisco"},
    "model": "Catalyst 3560-CX-12PC-S",
    "slug": "ws-c3560cx-12pc-s",
    "part_number": "WS-C3560CX-12PC-S",
    "u_height": 1,
    "is_full_depth": False,
    "interface": [
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/1",
            "type": "1000base-t",
            "mgmt_only": False,
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/2",
            "type": "1000base-t",
            "mgmt_only": False,
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/3",
            "type": "1000base-t",
            "mgmt_only": False,
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/4",
            "type": "1000base-t",
            "mgmt_only": False,
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/5",
            "type": "1000base-t",
            "mgmt_only": False,
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/6",
            "type": "1000base-t",
            "mgmt_only": False,
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/7",
            "type": "1000base-t",
            "mgmt_only": False,
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/8",
            "type": "1000base-t",
            "mgmt_only": False,
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/9",
            "type": "1000base-t",
            "mgmt_only": False,
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/10",
            "type": "1000base-t",
            "mgmt_only": False,
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/11",
            "type": "1000base-t",
            "mgmt_only": False,
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/12",
            "type": "1000base-t",
            "mgmt_only": False,
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/13",
            "type": "1000base-t",
            "mgmt_only": False,
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/14",
            "type": "1000base-t",
            "mgmt_only": False,
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/15",
            "type": "1000base-x-sfp",
            "mgmt_only": False,
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "GigabitEthernet1/0/16",
            "type": "1000base-x-sfp",
            "mgmt_only": False,
        },
    ],
    "console": [
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "con0",
            "type": "rj-45",
        },
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "con1",
            "type": "usb-mini-b",
        },
    ],
    "power": [
        {
            "device_type": {"model": "Catalyst 3560-CX-12PC-S"},
            "name": "PSU0",
            "type": "iec-60320-c16",
        }
    ],
    "front_port": [],
    "rear_port": [],
}

pp = {
    "manufacturer": {"name": "excel"},
    "model": "PP_Copper_1U",
    "slug": "pp_cop_1u",
    "part_number": "pp_copper_1u",
    "u_height": 1,
    "is_full_depth": False,
    "interface": [],
    "console": [],
    "power": [],
    "front_port": [
        {"device_type": {"model": "PP_Copper_1U"}, "name": 1, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 2, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 3, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 4, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 5, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 6, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 7, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 8, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 9, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 10, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 11, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 12, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 13, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 14, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 15, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 16, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 17, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 18, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 19, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 20, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 21, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 22, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 23, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 24, "type": "110-punch"},
    ],
    "rear_port": [
        {"device_type": {"model": "PP_Copper_1U"}, "name": 1, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 2, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 3, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 4, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 5, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 6, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 7, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 8, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 9, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 10, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 11, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 12, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 13, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 14, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 15, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 16, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 17, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 18, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 19, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 20, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 21, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 22, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 23, "type": "110-punch"},
        {"device_type": {"model": "PP_Copper_1U"}, "name": 24, "type": "110-punch"},
    ],
}
